apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lgtm-mimir
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: mimir-distributed
      targetRevision: 5.*
      helm:
        valueFiles:
          - $values/helm-values/lgtm/values-mimir.yaml
    - repoURL: https://github.com/hoonii2/argocd-kind.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
