apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todomaster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/hoonii2/argocd-kind.git
    targetRevision: main
    path: manifests/todomaster
  destination:
    server: https://kubernetes.default.svc
    namespace: todomaster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
